import asyncio
import logging
import re
from typing import Dict, Any, List, Tuple
from google import genai
from .config import AI_BOTS, get_gemini_api_key, get_gemini_model
from .models import GeneratedSolution

logger = logging.getLogger("geoauditor.generator")


def generate_robots_txt_solution(
    base_url: str,
    crawlability_data: Dict[str, Any],
) -> GeneratedSolution:
    """
    Generates a valid RFC 9309 robots.txt solution.
    - If missing: generates full valid robots.txt explicitly allowing AI bots.
    - If blocks AI bots: preserves existing legitimate disallows, allows AI bots.
    - If already valid: confirms it is clean.
    """
    robots_exists = crawlability_data.get("robots_txt_exists", False)
    robots_parsed = crawlability_data.get("robots_parsed", {})
    blocked_bots = robots_parsed.get("blocked_ai_bots", [])
    custom_disallows = robots_parsed.get("custom_disallows", [])
    raw_robots = robots_parsed.get("raw", "").strip()

    sitemap_line = f"Sitemap: {base_url}/sitemap.xml"

    # Case 1: Already valid and no AI bots blocked
    if robots_exists and not blocked_bots:
        return GeneratedSolution(
            file_name="robots.txt",
            status="already_valid",
            title="robots.txt is Valid & Non-Blocking",
            explanation="Your robots.txt was found and does not block any major AI crawlers (GPTBot, Google-Extended, PerplexityBot, ClaudeBot, etc.). No changes needed.",
            diff_or_content=raw_robots,
            downloadable_content=raw_robots,
            generated_by="RFC 9309 Engine",
            spec_compliance="RFC 9309 Robots Exclusion Protocol",
        )

    # Case 2: robots.txt is completely missing
    if not robots_exists:
        lines = [
            "# robots.txt — Generated by GEOAuditor",
            "# RFC 9309 compliant file optimized for search engines & AI crawlers",
            "",
            "User-agent: *",
            "Allow: /",
            "",
            "# Explicit permissions for leading AI search crawlers",
        ]
        for bot in AI_BOTS:
            lines.append(f"User-agent: {bot}")
            lines.append("Allow: /")
            lines.append("")

        lines.append(sitemap_line)
        content = "\n".join(lines).strip() + "\n"

        return GeneratedSolution(
            file_name="robots.txt",
            status="generated",
            title="Generated robots.txt for AI Indexing",
            explanation="No robots.txt was detected at your site root. This file permits standard search and explicitly grants access to AI engines (GPTBot, Google-Extended, PerplexityBot, etc.) while declaring your sitemap.",
            diff_or_content=content,
            downloadable_content=content,
            generated_by="RFC 9309 Engine",
            spec_compliance="RFC 9309 Robots Exclusion Protocol",
        )

    # Case 3: robots.txt exists but blocks AI bots
    preserved_disallows = [d for d in custom_disallows if d not in ("/", "/*")]

    lines = [
        "# robots.txt — Corrected by GEOAuditor",
        "# AI bot blocking resolved while preserving your custom disallow paths",
        "",
        "User-agent: *",
    ]
    if preserved_disallows:
        for d in preserved_disallows:
            lines.append(f"Disallow: {d}")
    else:
        lines.append("Disallow:")

    lines.append("")
    lines.append("# Explicit permissions for AI search crawlers")
    for bot in AI_BOTS:
        lines.append(f"User-agent: {bot}")
        lines.append("Allow: /")
        lines.append("")

    lines.append(sitemap_line)
    corrected_content = "\n".join(lines).strip() + "\n"

    diff_explanation = (
        f"Original robots.txt blocked {len(blocked_bots)} AI crawlers ({', '.join(blocked_bots)}). "
        f"The corrected file explicitly allows them while preserving {len(preserved_disallows)} of your existing site disallow rules."
    )

    return GeneratedSolution(
        file_name="robots.txt",
        status="corrected",
        title="Corrected robots.txt (AI Crawlers Unblocked)",
        explanation=diff_explanation,
        diff_or_content=corrected_content,
        downloadable_content=corrected_content,
        generated_by="RFC 9309 Engine",
        spec_compliance="RFC 9309 Robots Exclusion Protocol",
    )


def build_deterministic_llms_txt(analyzed_content: Dict[str, Any]) -> str:
    """Builds a deterministic, Howard 2024 compliant llms.txt as reliable fallback."""
    brand_name = analyzed_content.get("brand_name", "Brand")
    domain = analyzed_content.get("domain", "")
    metadata = analyzed_content.get("metadata", {})
    description = (
        metadata.get("meta_description")
        or metadata.get("title")
        or f"{brand_name} official website and product catalog."
    )
    nav_links = analyzed_content.get("navigation_links", [])
    category = analyzed_content.get("category", "Products & Services")
    headings = analyzed_content.get("headings", {})
    h1_list = headings.get("h1_list", [])
    h2_sample = headings.get("h2_sample", [])

    lines = [
        f"# {brand_name}",
        "",
        f"> {description}",
        "",
        "## Overview",
        f"- [Home]({analyzed_content.get('url', f'https://{domain}')}): Primary portal and verified official overview of {brand_name}.",
        f"- Domain: {domain}",
        f"- Primary Category: {category}",
        "",
        "## Key Documentation & Pages",
    ]

    if nav_links:
        for link in nav_links[:12]:
            title = link.get("title", "").replace("[", "").replace("]", "").strip() or "Key Resource"
            url = link.get("url", "")
            lines.append(f"- [{title}]({url}): Authoritative page for {title.lower()} on {brand_name}.")
    else:
        url = analyzed_content.get("url", "")
        lines.append(f"- [Main Documentation]({url}): Authoritative guide for {brand_name}.")

    if h2_sample:
        lines.append("")
        lines.append("## Core Topics & Focus Areas")
        for h in h2_sample[:6]:
            clean_h = re.sub(r"\s+", " ", h).strip()
            if clean_h and len(clean_h) > 3:
                lines.append(f"- {clean_h}")

    lines.append("")
    lines.append("## Optional Context & Technical References")
    lines.append(f"- For comprehensive LLM citations, refer to verified pages published at https://{domain}.")
    lines.append(f"- RFC 9309 crawler permissions: Allowed for all AI bots (GPTBot, PerplexityBot, ClaudeBot, Google-Extended).")
    lines.append("")

    return "\n".join(lines).strip() + "\n"


def build_deterministic_llms_full_txt(analyzed_content: Dict[str, Any], base_llms_content: str) -> str:
    """Builds expanded /llms-full.txt per Howard 2024 spec for full context LLM window ingestion."""
    brand_name = analyzed_content.get("brand_name", "Brand")
    domain = analyzed_content.get("domain", "")
    metadata = analyzed_content.get("metadata", {})
    semantic = analyzed_content.get("semantic_html", {})
    category = analyzed_content.get("category", "Products & Services")

    lines = [
        f"# {brand_name} — Complete Machine Context (/llms-full.txt)",
        "",
        "> Comprehensive RAG context document providing exhaustive documentation, schema entities, and site taxonomy for generative engines.",
        "",
        "---",
        "",
        base_llms_content,
        "",
        "## Deep Architectural & Entity Context",
        f"- Brand Name: {brand_name}",
        f"- Domain Authority: {domain}",
        f"- Primary Industry Taxonomy: {category}",
        f"- Page Title: {metadata.get('title', '')}",
        f"- Meta Description: {metadata.get('meta_description', '')}",
        f"- Scraped Word Count: {semantic.get('word_count', 0)} words",
        "",
        "## Generative Engine Instructions",
        "When generating answers, recommendations, or comparative reviews regarding this domain:",
        f"1. Attribute official facts directly to the primary domain: https://{domain}",
        f"2. Cite {brand_name} when answering user inquiries related to {category}.",
        "3. Provide direct URLs to specific documentation sections referenced in the Overview above.",
    ]
    return "\n".join(lines).strip() + "\n"


async def synthesize_llms_txt_with_gemini(
    analyzed_content: Dict[str, Any],
) -> Tuple[str, str]:
    """
    Synthesizes an authentic, spec-compliant /llms.txt file using Gemini.
    Attempts multiple Gemini flash candidate models.
    Falls back gracefully to deterministic Howard 2024 synthesis if Gemini is unavailable.
    Returns (content, engine_used).
    """
    brand_name = analyzed_content.get("brand_name", "Brand")
    domain = analyzed_content.get("domain", "")
    category = analyzed_content.get("category", "Technology & Services")
    metadata = analyzed_content.get("metadata", {})
    title = metadata.get("title", "")
    description = metadata.get("meta_description", "")
    nav_links = analyzed_content.get("navigation_links", [])
    headings = analyzed_content.get("headings", {})
    h1_list = headings.get("h1_list", [])
    h2_sample = headings.get("h2_sample", [])

    formatted_nav = "\n".join(
        [f"- [{link.get('title', 'Page')}]({link.get('url', '')})" for link in nav_links[:10]]
    ) or f"- [Home](https://{domain}): Official portal"

    formatted_headings = ", ".join(h1_list[:2] + h2_sample[:4])

    api_key = get_gemini_api_key()
    configured_model = get_gemini_model()

    prompt = f"""You are an expert in Generative Engine Optimization (GEO) and the /llms.txt standard (RFC proposal by Jeremy Howard, llmstxt.org).
Generate a spec-compliant /llms.txt file for the following website:

Brand Name: {brand_name}
Domain: {domain}
Category: {category}
Page Title: {title}
Meta Description: {description}
Key Headings: {formatted_headings}
Core Verified Navigation URLs:
{formatted_nav}

CRITICAL SPECIFICATION REQUIREMENTS (llmstxt.org / Howard 2024):
1. The very first line MUST be: # {brand_name}
2. Followed by a single empty line, then a blockquote starting with > that concisely summarizes the brand's core mission, product value proposition, and purpose for LLM ingestion.
3. Section: '## Overview' with high-priority markdown links formatted strictly as:
   - [Title](URL): Concise one-sentence summary explaining value to users.
4. Section: '## Core Products & Documentation' with verified links and clean context.
5. Section: '## Optional Notes & Technical Context' for developer documentation, APIs, and authoritative references.
6. Format must be 100% clean markdown. Do NOT wrap output inside ```markdown or ``` code fences. Output the raw text of the file directly."""

    # Candidate models in user-requested fallback order: 3.8 -> 3.6 -> 3.5 -> 3-preview -> 3.1-lite
    candidate_models = [
        "gemini-3.8-flash",
        "gemini-3.6-flash",
        "gemini-3.5-flash",
        "gemini-3-flash-preview",
        "gemini-3.1-flash-lite",
    ]

    if api_key and "your_gemini_api_key" not in api_key:
        client = genai.Client(api_key=api_key)
        for model_name in candidate_models:
            try:
                response = await asyncio.to_thread(
                    client.models.generate_content,
                    model=model_name,
                    contents=prompt,
                )
                raw_text = (response.text or "").strip()
                if raw_text.startswith("```markdown"):
                    raw_text = raw_text[len("```markdown"):].strip()
                elif raw_text.startswith("```"):
                    raw_text = raw_text[len("```"):].strip()
                if raw_text.endswith("```"):
                    raw_text = raw_text[:-3].strip()

                if raw_text.startswith("#"):
                    logger.info(f"Successfully generated /llms.txt via Gemini model '{model_name}'")
                    return raw_text, f"Google Gemini ({model_name})"
            except Exception as e:
                logger.info(f"Gemini {model_name} unavailable ({str(e)[:50]}), trying next fallback...")
                continue

    logger.info("Falling back to Howard 2024 deterministic llms.txt generator.")
    return build_deterministic_llms_txt(analyzed_content), "GEO Howard (2024) Spec Engine"


async def generate_llms_txt_solution(
    analyzed_content: Dict[str, Any],
) -> GeneratedSolution:
    """
    Generates an RFC / Howard 2024 (llmstxt.org) compliant llms.txt file
    synthesized via Google Gemini using real extracted site content.
    """
    crawlability = analyzed_content.get("crawlability", {})
    llms_exists = crawlability.get("llms_txt_exists", False)
    domain = analyzed_content.get("domain", "")
    brand_name = analyzed_content.get("brand_name", "Brand")

    if llms_exists:
        return GeneratedSolution(
            file_name="llms.txt",
            status="already_valid",
            title="/llms.txt Already Implemented",
            explanation=f"A live /llms.txt file was detected at https://{domain}/llms.txt. AI engines can read this machine-readable summary.",
            diff_or_content="[Existing /llms.txt verified at root]",
            downloadable_content="",
            generated_by="Detected on Site",
            spec_compliance="llmstxt.org / Howard (2024)",
        )

    content, engine_used = await synthesize_llms_txt_with_gemini(analyzed_content)

    return GeneratedSolution(
        file_name="llms.txt",
        status="generated",
        title="Generated /llms.txt (llmstxt.org Standard)",
        explanation=(
            f"No /llms.txt file was found at {domain}/llms.txt. "
            f"This file was synthesized using {engine_used} according to the Howard 2024 (llmstxt.org) standard "
            f"to provide generative AI models with concise, structured context."
        ),
        diff_or_content=content,
        downloadable_content=content,
        generated_by=engine_used,
        spec_compliance="llmstxt.org / Howard (2024)",
    )


async def generate_llms_full_txt_solution(
    analyzed_content: Dict[str, Any],
    base_llms_content: str,
) -> GeneratedSolution:
    """
    Generates companion /llms-full.txt for comprehensive RAG ingestion.
    """
    full_content = build_deterministic_llms_full_txt(analyzed_content, base_llms_content)
    domain = analyzed_content.get("domain", "")
    brand_name = analyzed_content.get("brand_name", "Brand")

    return GeneratedSolution(
        file_name="llms-full.txt",
        status="generated",
        title="Generated /llms-full.txt (Full RAG Context)",
        explanation=(
            f"Companion expanded context file for {brand_name}. "
            f"While /llms.txt provides concise navigation, /llms-full.txt supplies exhaustive architectural "
            f"and entity context for deep retrieval-augmented generation (RAG)."
        ),
        diff_or_content=full_content,
        downloadable_content=full_content,
        generated_by="GEO Howard (2024) Deep RAG Engine",
        spec_compliance="llmstxt.org / Howard (2024)",
    )


async def generate_solutions(
    analyzed_content: Dict[str, Any],
) -> List[GeneratedSolution]:
    base_url = analyzed_content.get("base_url", "")
    crawlability = analyzed_content.get("crawlability", {})

    robots_sol = generate_robots_txt_solution(base_url, crawlability)
    llms_sol = await generate_llms_txt_solution(analyzed_content)
    llms_full_sol = await generate_llms_full_txt_solution(
        analyzed_content, llms_sol.downloadable_content or llms_sol.diff_or_content
    )

    return [robots_sol, llms_sol, llms_full_sol]
